#!/bin/bash -e
# AUTHOR: FRANCISCO NETO
# EMAIL: netoralves@gmail.com

# VARIAVEIS DO KEYCLOAK - CONTAINER
KEYCLOAK_USER="admin"
KEYCLOAK_PASSWORD="admin"
KEYCLOAK_CONTAINER_NAME="keycloak"
KEYCLOAK_CONTAINER_HOSTNAME="keycloak.example.com"
JBOSS_USER="admin"
JBOSS_PASSWORD="admin"
SRC_HTTP_PORT="8080"
DST_HTTP_PORT="8080"
SRC_MGMT_PORT="9990"
DST_MGMT_PORT="9990"
VERSION_C_KEYCLOAK="1.0"
OPENLDAP_CONTAINER_NAME="ldap"

# BUILDING IMAGES
docker build ../keycloak/ -t netoralves/keycloak:${VERSION_C_KEYCLOAK}

# PROVISIONING KEYCLOAK CONTAINER
docker run -e KEYCLOAK_USER="${KEYCLOAK_USER}"  -e KEYCLOAK_PASSWORD="${KEYCLOAK_PASSWORD}" -e JBOSS_USER="${JBOSS_USER}"  -e JBOSS_PASSWORD="${JBOSS_PASSWORD}" --name "${KEYCLOAK_CONTAINER_NAME}" --hostname "${KEYCLOAK_CONTAINER_HOSTNAME}"  --link $OPENLDAP_CONTAINER_NAME:$OPENLDAP_CONTAINER_NAME -p $SRC_HTTP_PORT:$DST_HTTP_PORT -p $SRC_MGMT_PORT:$SRC_MGMT_PORT netoralves/keycloak:$VERSION_C_KEYCLOAK
